### ISSUE TITLE
Design Logo

### ISSUE THREAD

**Issue by jroesch** [uwsaml/uwsaml.github.io#3]
Luis said he had a plan for this, any temporary place holder ideas?

**Comment by jroesch** [comment]
@luisceze @ztatlock thoughts? we should at least put a placeholder on the website for the time being

**Comment by luisceze** [comment]
how about we just write SAML for now? and then I suggest we do 99designs :).

-Luis
________________________________

**Comment by tqchen** [comment]
ping @luisceze on the logo

**Comment by jroesch** [comment]
All done, check out the GH org and the website, I took a first stab at updating the logos.
